---
title: "Kenya"
output:
  html_notebook: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
Coenrolled<-read.csv("NK_TBRU Co-enrolled SIDs 2018_AUG_14.csv")
Coenrolled<-arrange(Coenrolled, TBRU.STUDY.ID)
```

```{r functions for data cleaning}
replace.btwn.tables<-function(datatable1, datatable2, var, ref.var, new.vals){
    library(dplyr)
    inter <- intersect(datatable1[,var], datatable2[,ref.var])
    tbl1a <- subset(datatable1, datatable1[,var] %in% inter)
    tbl1b <- subset(datatable1, !(datatable1[,var] %in% inter))
    tbl2  <- subset(datatable2, datatable2[,ref.var] %in% inter)
    tbl1a[,var] <- replace(x = tbl1a[,var],
                           list = (tbl1a[,var] %in% tbl2[,ref.var]),
                           values = as.character(tbl2[,new.vals]))
    new.table<-rbind(tbl1a, tbl1b)
}

replace.btwn.tables2<-function(datatable1, datatable2, id.var, ref.var, new.var, new.vals){
    library(dplyr)
    inter <- intersect(datatable1[,id.var], datatable2[,ref.var])
    tbl1a <- subset(datatable1, datatable1[,id.var] %in% inter)
    tbl1b <- subset(datatable1, !(datatable1[,id.var] %in% inter))
    tbl2  <- subset(datatable2, datatable2[,ref.var] %in% inter)
    tbl1a[,new.var] <- replace(x = tbl1a[,new.var],
                           list = (tbl1a[,id.var] %in% tbl2[,ref.var]),
                           values = as.character(tbl2[,new.vals]))
    new.table<-rbind(tbl1a, tbl1b)
}

splitter<-function(data,column,splitter,one=NULL,two=NULL,three=NULL,four=NULL){
        library(data.table)
        
        labels<-tstrsplit(data[,column], splitter)
        data[,one]<-labels[[1]]
        data[,two]<-labels[[2]]
        data[,three]<-labels[[3]]
        return(data)
}

```

```{r Helminth Both}
library(data.table)
library(plyr)
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
IgG<-read.csv("IgG.csv")
Hel_TBRU <- read.csv("TBRUKatoKatzResults 2017_AUG_18.csv")
Hel_NK <-read.csv("NK Helminth Database Download 01Feb2018.csv")

HEL<-rbind(Hel_TBRU,Hel_NK,fill=TRUE)


HEL<-splitter(HEL, "StudyID", "-", one="StudyID", two="Visit", three="Iteration")
#Hel<-separate(Hel,StudyID,c("studyID","visit","iteration"))
HEL<-dplyr::rename(HEL, HelminthPositive = HelmithPositive)%>%
    filter(Visit==0)

#
Egg<-aggregate(SchistosomaIntensity~StudyID,HEL,FUN=mean)

#Helminth
S = aggregate(SchistosomaPositive ~ StudyID, data = HEL, function(x) {
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

H = aggregate(HelminthPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

A = aggregate(AscarisPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

T = aggregate(TricurisPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

h = aggregate(HookwormPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

dfs<-list(H, A, T, S, h, IgG, Egg)
Helminth<-join_all(dfs, by="StudyID")
Helminth<-mutate(Helminth, Number=AscarisPositive + TricurisPositive + SchistosomaPositive + HookwormPositive)%>%
    arrange(StudyID)
Helminth$StudyID<-as.character(Helminth$StudyID)
Helminth<-replace.btwn.tables(Helminth, Coenrolled, "StudyID", "TBRU.STUDY.ID", "NK.STUDY.ID")
```

```{r QFT Both}
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
QFT1 <- read.csv("NK Study QFT Results 2018_SEP_03.csv")
QFT1<-splitter(QFT1, "StudyID", "-", one="StudyID", two="Visit")
QFT1<-arrange(QFT1, StudyID)%>%
    filter(Visit==0 & QualResult!=3)
QFT1<-replace.btwn.tables(QFT1, Coenrolled, "StudyID", "TBRU.STUDY.ID", "NK.STUDY.ID")
#after a lot of digging around with duplicates I noticed that one person was being coded incorrectly after this

QFT2<-read.csv("TBRU_QFTResults_Main 2017_AUG_18.csv")
QFT2<-splitter(QFT2, "StudyID", "-", one="StudyID", two="Visit")
QFT2<-arrange(QFT2, StudyID)%>%
    filter(Visit==0 & QualResult!=3)%>%
    select(-RecID) 
QFT2<-replace.btwn.tables(QFT2, Coenrolled, "StudyID", "TBRU.STUDY.ID", "NK.STUDY.ID")

QFT<-rbindlist(list(QFT1, QFT2), fill=TRUE)
#recode all coenrolled individuals Study IDs to be the NK version
#Keeps all entries for the baseline visit and removes all the entries with indeterminate QFT results
#Removes the one discrepent column between the two original tables
#There are complete entries in both original CSV documents so this removes those duplicates
QFT<-unique(QFT)
#There are still duplicated Study IDs though... deal with later

QFT$NIL <- gsub(">10","10", QFT$NIL)
QFT$TBAntigen <- gsub(">10","10", QFT$TBAntigen)
QFT$TBAntigen <- gsub(">77","NA", QFT$TBAntigen)
QFT$Mitogen <- gsub(">10","10", QFT$Mitogen)
QFT$TBAntigen <- as.numeric(QFT$TBAntigen)
QFT$Mitogen <- as.numeric(QFT$Mitogen)
QFT$NIL<-as.numeric(QFT$NIL)
#Do my own math because I don't trust people
QFT$QFT <- (QFT$TBAntigen-QFT$NIL)
QFT$Control <- (QFT$Mitogen-QFT$NIL)
QFT$QFT[QFT$QFT<0]<-0
QFT$Control[QFT$Control<0]<-0

#Recode TB outcomes based on their new calculated Quantiferon scores
QFT$QualResult[QFT$QFT>0.35]<- 1
QFT$QualResult[QFT$QualResult==1] <- as.character("LTBI")
QFT$QualResult [QFT$QFT<0.35]<- 2
QFT$QualResult[QFT$QualResult==2] <- as.character("HEALTHY CONTROL")

QFT$StudyID<-as.character(QFT$StudyID)
```

```{r HIV TBRU}
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
HIV_TBRU <- read.csv("TBRU HIV TEST RESULTS_2017_JAN_11.csv")
HIV_TBRU$StudyID<-as.character(HIV_TBRU$StudyID)
HIV_TBRU<-arrange(HIV_TBRU, StudyID)
HIV_TBRU<-replace.btwn.tables(HIV_TBRU, Coenrolled, "StudyID", "TBRU.STUDY.ID", "NK.STUDY.ID")
HIV_TBRU <-filter(HIV_TBRU, CurrVisit!="2")
HIV_TBRU$HIVResult<-gsub("1", "POS", HIV_TBRU$HIVResult)
HIV_TBRU$HIVResult<-gsub("2", "NEG", HIV_TBRU$HIVResult)
```

```{r Enrollment both}
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
TBRU<-read.csv("TBRU PARTICIPANT INFORMATION.csv")
TBRU$StudyID<-as.character(TBRU$StudyID)
TBRU<-arrange(TBRU, StudyID)
TBRU<-replace.btwn.tables(TBRU, Coenrolled, "StudyID", "TBRU.STUDY.ID", "NK.STUDY.ID")

Enrollment<-read.csv("NK Cell Study Enrollment Summary 2018_MAY_01.csv")
Enrollment<-rename(Enrollment, StudyID = STUDY.ID)
Enrollment$StudyID<-as.character(Enrollment$StudyID)

both<-read.csv("TBRU & NK Cohort Information.csv")
both$StudyID<-as.character(both$StudyID)
both<-arrange(both, StudyID)
both<-replace.btwn.tables(both, Coenrolled, "StudyID", "TBRU.STUDY.ID", "NK.STUDY.ID")

both<-rename(both, IgG.both = IgG, OD.both =OD)
Cohort<-read.csv("NK Cohort Samples.csv")
Cohort$StudyID<-as.character(Cohort$StudyID)

dfs<-list(TBRU, Cohort, both, Enrollment )
cohort<-join_all(dfs, by="StudyID", type="full")
```

```{r Merge remove pilot samples duplicates and misentered participants}
library(dplyr)
dfs<-list(cohort, QFT, HIV_TBRU, Helminth)
Total<-join_all(dfs, by="StudyID", type="full")

library(dplyr)
#questionable entries
LabNos<-list("NKS0122","NKS0745", "NKS0416", "NKS1213", "TRU01090")
IDs<-list("NK2464","NK2712", "NK227", "NK26", "NKS2754", "NK2925", "NK2493")
#pilot samples
pilot<-list("NK2000","NK2001", "NK2002", "NK2003","NK2004", "NK2005", "NK2006","NK2007", "NK2008", "NK2009","NK2010", "NK2011", "NK2012","NK2013", "NK2014", "NK2015","NK2016")
dups_before<-Total$StudyID[duplicated(Total$StudyID)]

Total<-dplyr::filter(Total, !(LabNo %in% LabNos)) %>%
  dplyr::filter(!StudyID %in% IDs) %>%
    dplyr::filter(!(StudyID %in% pilot))

Total<-select(Total, -DATE.CONSENTED, -ResultDate, -EntryDate, -Created, -Modified, -RowVersion,-DateFormFilled, -HIVtestDate, -DateQCDone)
Total<-unique(Total)

dups_after<-Total$StudyID[duplicated(Total$StudyID)]
dups_Total<-filter(Total, StudyID %in% dups_after)
doublecheck<-Total
```

```{r for loops to combine HIV/TB data}
library(dplyr)
Total$age<-NA
for (i in 1:length(Total$age)){
    if(!is.na(Total$AGE[i])){
        Total$age[i] <- Total$AGE[i]}
    
    else{
        Total$age[i] <- Total$Age[i]} 
} 

Total$sex<-NA
for (i in 1:length(Total$sex)){
    if(!is.na(Total$SEX[i])){
        Total$sex[i] <- as.character(Total$SEX[i])}
    
    else if(!is.na(Total$Gender[i])){
        Total$sex[i] <- as.character(Total$Gender[i])} 

    else{
        Total$sex[i] <- as.character(Total$Sex[i])} 
}
#From Cheryl... 1=male; 2=female
Total$sex<-gsub("1","M", Total$sex)
Total$sex<-gsub("2","F", Total$sex)

Total$HIV<-NA
for (i in 1:length(Total$HIV)){
    if(!is.na(Total$HIV.status[i])){
        Total$HIV[i] <- as.character(Total$HIV.status[i])}
    
    else if(!is.na(Total$HIVResult[i])){
        Total$HIV[i] <- Total$HIVResult[i]} 
    
    else{
        Total$HIV[i] <- as.character(Total$HIV.STATUS[i])} 
}
#From Cheryl unless desginated positive all TRU study participants are negative
Total$HIV[Total$Study=="TRU" & is.na(Total$HIV)]<-"NEG"
#From Cheryl 0 means test not done
Total$HIV<-gsub("0", "NA", Total$HIV)

Total$cd4<-NA
for (i in 1:length(Total$cd4)){
    if(!is.na(Total$CD4[i])){
        Total$cd4[i] <- as.character(Total$CD4[i])}    
    else{
        Total$cd4[i] <- as.character(Total$CD4.COUNT[i])} 
}

Total$viral.load<-NA
for (i in 1:length(Total$viral.load)){
    if(!is.na(Total$VL[i])){
        Total$viral.load[i] <- as.character(Total$VL[i])}
    
    else{
        Total$viral.load[i] <- as.character(Total$Viral.Load[i])} 
}

Total$ART<-NA
for (i in 1:length(Total$ART)){
    if(!is.null(Total$On.Art.[i])){
        Total$ART[i] <- Total$On.Art[i]}
    
    else if(!is.na(Total$ARTInitiated[i])){
        Total$ART[i] <- "No"[i]} 
} 

Total$IPT<-NA
for(i in 1:length(Total$IPT)){
    if(!is.na(Total$IPTInitiated[i])){
        Total$IPT[i]<-Total$IPTInitiated[i]}
        
    else if(!is.na(Total$ON.ANTI.TB.DRUGS[i])){
        Total$IPT[i] <- Total$ON.ANTI.TB.DRUGS[i]}    
}

Total$TB<-NA
for (i in 1:length(Total$TB)){
    if(!is.na(Total$QualResult[i])){
        Total$TB[i] <- as.character(Total$QualResult[i])}
    
    else if(!is.na(Total$SCREENING.ARM[i])){
        Total$TB[i] <- as.character(Total$SCREENING.ARM[i])} 
      
    else if(!is.na(Total$Screening.Arm[i])){
        Total$TB[i] <- as.character(Total$Screening.Arm[i])} 
    
    else{
        Total$TB[i] <- as.character(Total$QFT.RESULTS[i])} 
}
```

```{r antibiotic resistance}
Total$chest.xray<-tolower(Total$CXR.REPORT)
Total$chest.xray[grepl("abnormal|cardiomegaly", Total$chest.xray)]<-"abnormal"
Total$chest.xray[grepl("n/a|not done", Total$chest.xra)]<-NA
Total$chest.xray[grepl("no", Total$chest.xra) &! grepl("rmal", Total$chest.xra)]<-NA

Total$gene.expert<-tolower(Total$EXPERT.RESULTS)
Total$gene.expert[grepl("n/a|no sample|error", Total$gene.expert)]<-NA
Total$gene.expert[grepl("no rif", Total$gene.expert)]<-"rif sensitive"

Total$hain<-tolower(Total$HAIN.TEST.RESULTS)
Total$hain[grepl("invalid|n/a|no sample", Total$hain)]<-NA

Total$mgit<-tolower(Total$MGIT.Culture)
Total$mgit[grepl("mott", Total$mgit)]<-"NTM"
Total$mgit[grepl("pos", Total$mgit)]<-"MTB"
Total$mgit[grepl("culture contaminated|n/a|no sample", Total$mgit)]<-NA

Total$microscopy<-tolower(Total$FM..RESULTS)
Total$microscopy[grepl("n/a|no sample", Total$microscopy)]<-NA

Total$INH.Resistant<-NA
for(i in 1:length(Total$INH.Resistant)){
    if(grepl("resistant to inh", Total$hain[i])){
        Total$INH.Resistant[i]<-1}
    
    else if(grepl("sensitive to inh", Total$hain[i])){
        Total$INH.Resistant[i]<-0}
    
    else {Total$INH.Resistant[i]<-NA}
}

Total$Rif.Resistant<-NA
for(i in 1:length(Total$Rif.Resistant)){
    if(grepl("resistant to rif", Total$hain[i])){
        Total$Rif.Resistant[i]<-1}
    
    else if(grepl("sensitive to rif", Total$hain[i])){
        Total$Rif.Resistant[i]<-0}
        
    else if(grepl("sensitive to inh and rif", Total$hain[i])){
        Total$Rif.Resistant[i]<-0}
    
    else if(grepl("rif sensitive", Total$gene.expert[i])){
        Total$Rif.Resistant[i]<-0}    

    else {Total$Rif.Resistant[i]<-NA}
}

Total$Drug.Resistant<-NA
for(i in 1:length(Total$Drug.Resistant)){
    if(!is.na(Total$INH.Resistant[i]) & Total$INH.Resistant[i]==1){
        Total$Drug.Resistant[i]<-1}
    
    else if(!is.na(Total$Rif.Resistant[i]) & Total$Rif.Resistant[i]==1){
        Total$Drug.Resistant[i]<-1}
    
    else if(!is.na(Total$gene.expert[i]) & Total$gene.expert[i]=="pos"){
        Total$Drug.Resistant[i]<-1} 
    
    else if(!is.na(Total$INH.Resistant[i]) & Total$INH.Resistant[i]=="0" &
            !is.na(Total$Rif.Resistant[i]) & Total$Rif.Resistant[i]=="0"){
        Total$Drug.Resistant[i]<-0}

    else {Total$Drug.Resistant[i]<-NA}
}
Total$Days.to.MGIT.Culture.<-as.numeric(as.character((Total$Days.to.MGIT.Culture.)))
```

```{r updating study and location data}
#From Cheryl SIDs starting with ‘8’ or ‘3’ were enrolled at CRC; all TBRU SIDs starting with ‘4’ were enrolled at Kombewa.
Total$SCREENING.SITE[grepl("8|3", Total$StudyID)]<-"JOOTRH"
Total$SCREENING.SITE[grepl("4", Total$StudyID)]<-"KOMBEWA"

setwd("/Applications/Old Computer/Epi Project/Data_original/")
location<-read.csv("NK Study Enrollment Details CRF 2018_SEP_19.csv")
#Participants in the NK study were also enrolled at either CRC or Kombewa. I’ve attached an Excel spreadsheet of the enrollment details that are entered in the database for the NK study SIDs: under the Facilities columns, 1 and 2 = JOOTRH/CRC and 4 and 5 = Kombewa (or Kombewa County Hospital, same thing)
location$facility[grepl("1|2", location$Facility)]<-"JOOTRH"
location$facility[grepl("4|5", location$Facility)]<-"KOMBEWA"
location<-arrange(location, StudyID)

Total<-replace.btwn.tables2(Total, location, "StudyID", "StudyID", "SCREENING.SITE", "facility")

Total$Study[grepl("NK", Total$StudyID)]<-"NKS"
Total$Study[grepl("30|40|80", Total$StudyID)]<-"TRU"


```

```{r dummy variables}
Total$HC <-NA
for (i in 1:length(Total$HC)){
    if (is.na(Total$TB[i])){
        Total$HC[i] <- NA}
    else if (Total$TB[i] =="HEALTHY CONTROL"){
        Total$HC[i] <- 1}
    else if (Total$TB[i] =="LTBI"){
        Total$HC[i] <- 0}
    else if (Total$TB[i] =="ACTIVE"){
        Total$HC[i] <- 0}
    else Total$HC[i] <- NA
}

Total$LTBI <-NA
for (i in 1:length(Total$LTBI)){
    if (is.na(Total$TB[i])){
        Total$LTBI[i] <- NA}
    else if (Total$TB[i] =="HEALTHY CONTROL"){
        Total$LTBI[i] <- 0}
    else if (Total$TB[i] =="LTBI"){
        Total$LTBI[i] <- 1}
    else if (Total$TB[i] =="ACTIVE"){
        Total$LTBI[i] <- 0}
    else Total$LTBI[i] <- NA
}

Total$ATB <-NA
for (i in 1:length(Total$ATB)){
    if (is.na(Total$TB[i])){
        Total$ATB[i] <- NA}
    else if (Total$TB[i] =="HEALTHY CONTROL"){
        Total$ATB[i] <- 0}
    else if (Total$TB[i] =="LTBI"){
        Total$ATB[i] <- 0}
    else if (Total$TB[i] =="ACTIVE"){
        Total$ATB[i] <- 1}
    else Total$ATB[i] <- NA
}
```

```{r adding in age by hand}
Total$age[Total$StudyID=="NK2738"]<-35
Total$age[Total$StudyID=="NK2812"]<-20
Total$age[Total$StudyID=="NK2819"]<-22
Total$age[Total$StudyID=="NK2841"]<-20
```

```{r implicit knowns}
Total$viral.load[Total$HIV=="NEG"]<-0
```

```{r Separate into Data Tables to get missing data}
#Missing values
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_clean/")
library(dplyr)
Dates<-select(Total, StudyID, Date.Consented, Date.Enrolled, ART.Start.Date, DATE.ANTI.TB.STARTED, Days.on.TB.Tx)

Total<-select(Total, -UserCode, -CurrVisit, -FollUpVisit, -StaffInitials, -HIVtestDone, -ReasonTestND, -OtherReasonTestND, -Comments, -QCStaffInitials, -EntryUserInitials, CPTs.Collected, Cell.Counts..x10.6., Baseline.Completion.Report, Sample.Storage, -IgG.both, -OD.both, -Date.Enrolled, -REASON, -CPTs.Collected, -Cell.Counts..x10.6., -Baseline.Completion.Report, -Sample.Storage, -STATUS, -Visit, -RecID, -COENRLD.STUDY, -Date.Consented, -Date.Enrolled, -ART.Start.Date, -DATE.ANTI.TB.STARTED, -REFERRAL.POINT, -QFTType, -TBAntigen2, -QualResult, -SCREENING.ARM, -Screening.Arm, -QFT.RESULTS, -IPTInitiated, -ON.ANTI.TB.DRUGS, -On.ART., -ARTInitiated, -AGE, -Age, -SEX, -Gender, -Sex, -HIV.status, -HIVResult, -HIV.STATUS, -CD4, -CD4.COUNT, -VL, -Viral.Load)###Still need to remove original TB exam columns

TB.missing<-select(Total, StudyID, TB, CXR.REPORT, FM..RESULTS, EXPERT.RESULTS, HAIN.TEST.RESULTS, MGIT.Culture, Days.on.TB.Tx, Household.contact.treated.for.TB.within.past.2.yrs, Treated.for.TB.Previously., NIL, TBAntigen, Mitogen, QFT)%>%
    filter(is.na(TB)|is.na(QFT)|is.na(CXR.REPORT))

Hel.missing<-select(Total, StudyID, HelminthPositive, AscarisPositive, TricurisPositive, SchistosomaPositive, HookwormPositive, SchistosomaIntensity)%>%
    filter(is.na(HelminthPositive))

Demographic.missing<-select(Total, StudyID, age, sex, SCREENING.SITE, RACE,
                            MAL.TEST.RESULTS, PT.RESULT, Hb)%>%
    filter(is.na(RACE) | is.na(age) | is.na(SCREENING.SITE) | is.na(Hb))

HIV.missing<-select(Total, StudyID, HIV, cd4, viral.load, WHO.STAGE)%>%
    filter(!(WHO.STAGE %in% c("1","3")))%>%
    filter(HIV!="NEG")

#have to run these at the console for whatever reason
write.csv(Dates, "dates.csv")
write.csv(TB.missing, "missing-tb.csv")
write.csv(Hel.missing, "missing-helminth.csv")
write.csv(Demographic.missing, "missing-demographic.csv")
write.csv(HIV.missing, "missing-HIV.csv")
write.csv(Total, "complete-kenya.csv")

sumNA<-colSums(is.na(Total))
miss.var<-rbind(names(Total), sumNA)
sumNA2<-rowSums(is.na(Total))
miss.donor<-cbind(Total$StudyID, sumNA2)
```


