---
title: "Kenya"
output:
  html_notebook: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
Coenrolled<-read.csv("NK_TBRU Co-enrolled SIDs 2018_AUG_14.csv")
Coenrolled<-arrange(Coenrolled, TBRU.STUDY.ID)
Coenrolled$Joint.Study.ID<-paste(Coenrolled$NK.STUDY.ID, Coenrolled$TBRU.STUDY.ID, sep="_")
```

```{r functions for data cleaning}
source("/Users/tarynam/Desktop/Miscellaneous-Scripts/tryna function.R")
```

```{r Helminth Both}
library(data.table)
library(plyr)
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
IgG<-read.csv("IgG.csv")
Hel_TBRU <- read.csv("TBRUKatoKatzResults 2017_AUG_18.csv")
Hel_NK <-read.csv("NK Helminth Database Download 01Feb2018.csv")

HEL<-rbind(Hel_TBRU,Hel_NK,fill=TRUE)


HEL<-splitter(HEL, "StudyID", "-", one="StudyID", two="Visit", three="Iteration")
#Hel<-separate(Hel,StudyID,c("studyID","visit","iteration"))
HEL<-dplyr::rename(HEL, HelminthPositive = HelmithPositive)%>%
    filter(Visit==0)

#
Egg<-aggregate(SchistosomaIntensity~StudyID,HEL,FUN=mean)

#Helminth
S = aggregate(SchistosomaPositive ~ StudyID, data = HEL, function(x) {
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

H = aggregate(HelminthPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

A = aggregate(AscarisPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

T = aggregate(TricurisPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

h = aggregate(HookwormPositive ~ StudyID, data = HEL, function(x) {
  
  if (1 %in% x) {
    return(1);
  } else {
    return(0);
  }
});

dfs<-list(H, A, T, S, h, IgG, Egg)
Helminth<-join_all(dfs, by="StudyID")
Helminth<-mutate(Helminth, Number=AscarisPositive + TricurisPositive + SchistosomaPositive + HookwormPositive)%>%
    arrange(StudyID)
Helminth$StudyID<-as.character(Helminth$StudyID)
Helminth<-replace.btwn.tables(Helminth, Coenrolled, "StudyID", "TBRU.STUDY.ID", "StudyID", "Joint.Study.ID")
```

```{r QFT Both}
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")
QFT1a <- read.csv("NK Study QFT Results 2018_SEP_03.csv")
QFT1a <-splitter(QFT1a, "StudyID", "-", one="StudyID", two="Visit")
QFT1a <-arrange(QFT1a, StudyID)%>%
    filter(Visit==0 & QualResult!=3)
QFT1b <-read.csv("NK QFTData_Clinical Database.csv")
inter<-intersect(QFT1a$StudyID, QFT1b$StudyID)
QFT1b <- filter(QFT1b, !(StudyID %in% inter))%>%
    dplyr::rename(TBAntigen = TBAg) %>%
    dplyr::filter(TBAntigen < 10 | Mitogen < 10)%>%
    dplyr::mutate(Study="NKS")%>%
    dplyr::select(RecID , StudyID , ResultDate , NIL , TBAntigen , Mitogen, UserCode, EntryDate, Created, Modified , RowVersion)
l<-list(QFT1a, QFT1b)
QFT1<-data.frame(rbindlist(l, fill = TRUE))
QFT1$StudyID<-as.character(QFT1$StudyID)
QFT1<-replace.btwn.tables(QFT1, Coenrolled, "StudyID", "NK.STUDY.ID", "StudyID", "Joint.Study.ID")
#after a lot of digging around with duplicates I noticed that one person was being coded incorrectly after this

QFT2a<-read.csv("TBRU_QFTResults_Main 2017_AUG_18.csv")
QFT2b<-read.csv("TBRUKE_Data_Main_C50.csv")
#QFT2c<-read.csv("TBRUKE_Data_Main_QFT_Lab_db.csv") --->>> same as QFT2a except date entries
QFT2a<-splitter(QFT2a, "StudyID", "-", one="StudyID", two="Visit")
QFT2a<-dplyr::filter(QFT2a, Visit!="s",  Visit!="S", QualResult!=3)%>%
    filter(RecID!=3629)

QFT2b<-dplyr::rename(QFT2b, NIL = Nil, TBAntigen = TBAg, QualResult = QFTResult, 
                     Visit = CurrVisit, ResultDate = QFTResultDate, QFTType = QFTTestUsed)%>%
    filter(is.na(Visit)|Visit==1, QualResult!=3)%>%
    filter(RecID!=11, RecID!=22, RecID!=16, RecID!=76, RecID!=175, RecID!=128, RecID!=4345,
           RecID!=4351, RecID!=89, RecID!=95, RecID!=90, RecID!=3344, RecID!=144,
           RecID!=124, RecID!=139, RecID!=1272, RecID!=5354, RecID!=211)%>%
    filter((StudyID %in% QFT2a$StudyID)==FALSE)

##code to find duplicates in each table
QFT2<-rbindlist(list(QFT2a, QFT2b), fill=TRUE)
QFT2<-as.data.frame(arrange(QFT2, StudyID))
#recode all coenrolled individuals Study IDs to be the NK version
QFT2<-replace.btwn.tables(QFT2, Coenrolled, "StudyID", "TBRU.STUDY.ID", "StudyID", "Joint.Study.ID")
QFT2<-filter(QFT2, !(StudyID %in% intersect(QFT1$StudyID, QFT2$StudyID)))

QFT<-rbindlist(list(QFT1, QFT2), fill=TRUE)
#Removes the one discrepent column between the two original tables
QFT<-dplyr::select(QFT, -RecID)
#There are complete entries in both original CSV documents so this removes those duplicates
QFT<-unique(QFT)
#There are still duplicated Study IDs though... deal with later

QFT$NIL <- gsub(">10","10", QFT$NIL)
QFT$TBAntigen <- gsub(">10","10", QFT$TBAntigen)
QFT$TBAntigen <- gsub(">77","NA", QFT$TBAntigen)
QFT$Mitogen <- gsub(">10","10", QFT$Mitogen)
QFT$TBAntigen <- as.numeric(QFT$TBAntigen)
QFT$Mitogen <- as.numeric(QFT$Mitogen)
QFT$NIL<-as.numeric(QFT$NIL)
#Do my own math because I don't trust people
QFT$QFT <- (QFT$TBAntigen-QFT$NIL)
QFT$Control <- (QFT$Mitogen-QFT$NIL)
QFT$QFT[QFT$QFT<0]<-0
QFT$Control[QFT$Control<0]<-0

#Recode TB outcomes based on their new calculated Quantiferon scores
QFT$QualResult[QFT$QFT>0.35]<- 1
QFT$QualResult[QFT$QualResult==1] <- as.character("LTBI")
QFT$QualResult [QFT$QFT<0.35]<- 2
QFT$QualResult[QFT$QualResult==2] <- as.character("HEALTHY CONTROL")

QFT$StudyID<-as.character(QFT$StudyID)
```

```{r demographic NK}
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")

Enrollment<-read.csv("NK Cell Study Enrollment Summary 2018_MAY_01.csv")
Enrollment<-dplyr::rename(Enrollment, StudyID = STUDY.ID, 
                          HHC = Household.contact.treated.for.TB.within.past.2.yrs)

both<-read.csv("TBRU & NK Cohort Information.csv")
both$StudyID<-as.character(both$StudyID)
both<-arrange(both, StudyID)
both<-dplyr::select(both, -IgG, -OD)

age<-subset(both, grepl("NK", both$StudyID)==TRUE)

hiv<-read.csv("NK Cohort Samples.csv")

xray<-read.csv("NK Study CXRreadingData_Clinical Database.csv")
xray<-dplyr::select(xray, StudyID, Interpretation)%>%
    dplyr::rename(chest = Interpretation)
xray$chest<-gsub( 1, "NORMAL", xray$chest)
xray$chest<-gsub( 2, "ABNORMAL", xray$chest)
xray$chest<-gsub( 3, "NOT TB", xray$chest)

dfs<-list(Enrollment, age, hiv, xray)
NK<-join_all(dfs, by="StudyID", type="full")
NK<-replace.btwn.tables(NK, Coenrolled, "StudyID", "NK.STUDY.ID", "StudyID", "Joint.Study.ID")

#remove(Enrollment, age, hiv, xray, both, dfs)
```

```{r demographic TBRU}
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_original/")

TRU<-read.csv("TBRU PARTICIPANT INFORMATION.csv")
TRU$StudyID<-as.character(TRU$StudyID)
TRU<-dplyr::arrange(TRU, StudyID)

hiv<- read.csv("TBRU HIV TEST RESULTS_2017_JAN_11.csv")
hiv$StudyID<-as.character(hiv$StudyID)
hiv <-dplyr::filter(hiv, CurrVisit==1)
hiv$HIVResult<-gsub("1", "POS", hiv$HIVResult)
hiv$HIVResult<-gsub("2", "NEG", hiv$HIVResult)

pt<-read.csv("C38_PREG TEST RESULTS.csv")
pt<-dplyr::filter(pt, CurrVisit == 1)%>%
    dplyr::select(StudyID, PregTestDone, ReasonTestND, PregTestResult)%>%
    dplyr::rename(PT.RESULT = PregTestResult)
#1 = positive, 2 = negative
pt$PT.RESULT<-gsub(1, "POS", pt$PT.RESULT)
pt$PT.RESULT<-gsub(2, "NEG", pt$PT.RESULT)

xray<-read.csv("C55_CXR RESULTS.csv")
xray<-dplyr::filter(xray, CurrVisit == 1)%>%
    dplyr::select(StudyID, CXRDone, OtherReasXRayND, CXRResult)%>%
    dplyr::rename(chest = CXRResult)
#1 = normal, 2=abnormal
xray$chest<-gsub( 1, "NORMAL", xray$chest)
xray$chest<-gsub( 2, "ABNORMAL", xray$chest)
xray$chest<-gsub( 3, "NOT TB", xray$chest)

hb<-read.csv("C36_HB RESULTS.csv")
hb<-dplyr::filter(hb, CurrVisit == 1)%>%
    dplyr::select(StudyID, HbResult)%>%
    dplyr::rename(Hb = HbResult)
hb<-aggregate(Hb~StudyID, data=hb, FUN=mean)

exp<-read.csv("C34_BASELINE TB EXPOSURE.csv")
exp<- dplyr::select(exp, StudyID, TBCaseLst3Mnths)%>%
    dplyr::rename(HHC = TBCaseLst3Mnths)
exp$HHC <- gsub("1", "Yes", exp$HHC)
exp$HHC <- gsub("2", "No", exp$HHC)

dfs<-list(TRU, hiv, pt, xray, hb, exp)
TBRU<-join_all(dfs, by="StudyID", type="full")
TBRU<-arrange(TBRU, StudyID)
TBRU<-replace.btwn.tables(TBRU, Coenrolled, "StudyID", "TBRU.STUDY.ID", "StudyID","Joint.Study.ID")
#remove(TRU, pt, xray, hb, exp, hiv, dfs)
```

```{r demographic both}
library(dplyr)
inter<-intersect(NK$StudyID, TBRU$StudyID)
NK_both<-filter(NK, StudyID %in% inter)
TBRU_both<-filter(TBRU, StudyID %in% inter)
both<-merge(NK_both, TBRU_both, by="StudyID")
NK_unique<-filter(NK, !StudyID %in% inter)
TBRU_unique<-filter(TBRU, !StudyID %in% inter)
dfs<-list(NK_unique, TBRU_unique, both)
cohort<-as.data.frame(rbindlist(dfs, fill=TRUE))
cohort<-replace.btwn.tables(cohort, Coenrolled, "StudyID", "NK.STUDY.ID", "StudyID", "Joint.Study.ID")
cohort<-replace.btwn.tables(cohort, Coenrolled, "StudyID", "TBRU.STUDY.ID", "StudyID", "Joint.Study.ID")
```

```{r Merge remove pilot samples duplicates and misentered participants}
library(dplyr)
dfs<-list(cohort, QFT, Helminth)
Total<-join_all(dfs, by="StudyID", type="full")

library(dplyr)
#questionable entries
LabNos<-list("NKS0122","NKS0745", "NKS0416", "NKS1213", "TRU01090")
IDs<-list("NK2464","NK2712", "NK227", "NK26", "NKS2754", "NK2925", "NK2493")
#pilot samples
pilot<-list("NK2000","NK2001", "NK2002", "NK2003","NK2004", "NK2005", "NK2006","NK2007", "NK2008", "NK2009","NK2010", "NK2011", "NK2012","NK2013", "NK2014", "NK2015","NK2016")
dups_before<-Total$StudyID[duplicated(Total$StudyID)]

Total<-dplyr::filter(Total, !(LabNo %in% LabNos)) %>%
    dplyr::filter(!StudyID %in% IDs) %>%
    dplyr::filter(!(StudyID %in% pilot))%>%
    dplyr::select(-DATE.CONSENTED, -ResultDate, -EntryDate, -Created, -Modified, -RowVersion,-DateFormFilled, -HIVtestDate, -DateQCDone)
Total<-unique(Total)

dups_after<-Total$StudyID[duplicated(Total$StudyID)]
dups_Total<-filter(Total, StudyID %in% dups_after)
doublecheck<-Total
```

```{r dealing with different NA nomenclature}
Total[Total==""]<-NA
Total[Total=="PENDING"]<-NA
Total[Total=="pending"]<-NA

Total$SCREENING.SITE[grepl("PENDING", Total$SCREENING.SITE)]<-NA

Total$WHO.STAGE<-as.character(Total$WHO.STAGE)
Total$WHO.STAGE[grepl("N/", Total$WHO.STAGE)]<-NA

Total$MAL.TEST.RESULTS[grepl("PENDING", Total$MAL.TEST.RESULTS)]<-NA

Total$PT.RESULT[grepl("PENDING|N/A", Total$PT.RESULT)]<-NA

Total$Hb[grepl("PENDING|Other", Total$Hb)]<-NA

Total$CD4[grepl("N/A", Total$CD4)]<-NA
Total$CD4.COUNT[grepl("N/A", Total$CD4.COUNT)]<-NA
Total$CD4.COUNT[grepl("Other", Total$CD4.COUNT)]<-NA
```

```{r updating study and location data}
#From Cheryl SIDs starting with ‘8’ or ‘3’ were enrolled at CRC; all TBRU SIDs starting with ‘4’ were enrolled at Kombewa.
Total$SCREENING.SITE[grepl("8|3", Total$StudyID)]<-"JOOTRH"
Total$SCREENING.SITE[grepl("4", Total$StudyID)]<-"KOMBEWA"

setwd("/Applications/Old Computer/Epi Project/Data_original/")
location<-read.csv("NK Study Enrollment Details CRF 2018_SEP_19.csv")
#Participants in the NK study were also enrolled at either CRC or Kombewa. I’ve attached an Excel spreadsheet of the enrollment details that are entered in the database for the NK study SIDs: under the Facilities columns, 1 and 2 = JOOTRH/CRC and 4 and 5 = Kombewa (or Kombewa County Hospital, same thing)
location$facility[grepl("1|2", location$Facility)]<-"JOOTRH"
location$facility[grepl("4|5", location$Facility)]<-"KOMBEWA"
location<-dplyr::select(location, StudyID, facility)%>%arrange(StudyID)
location<-unique(location)

Total<-replace.btwn.tables(Total, location, "StudyID", "StudyID", "SCREENING.SITE", "facility")

Total$Study[grepl("30|40|80", Total$StudyID)]<-"TRU"
Total$Study[grepl("NK", Total$StudyID)]<-"NKS"
```

```{r for loops to combine data}
library(dplyr)
Total$age<-NA
for (i in 1:length(Total$age)){
    if(!is.na(Total$AGE[i])){
        Total$age[i] <- Total$AGE[i]}
    
    else{
        Total$age[i] <- Total$Age[i]} 
} 

Total$sex<-NA
for (i in 1:length(Total$sex)){
    if(!is.na(Total$SEX[i])){
        Total$sex[i] <- as.character(Total$SEX[i])}
    
    else if(!is.na(Total$Gender[i])){
        Total$sex[i] <- as.character(Total$Gender[i])} 

    else{
        Total$sex[i] <- as.character(Total$Sex[i])} 
}
#From Cheryl... 1=male; 2=female
Total$sex<-gsub("1","M", Total$sex)
Total$sex<-gsub("2","F", Total$sex)

Total$HIV<-NA
for (i in 1:length(Total$HIV)){
    if(!is.na(Total$HIV.status[i])){
        Total$HIV[i] <- as.character(Total$HIV.status[i])}
    
    else if(!is.na(Total$HIVResult[i])){
        Total$HIV[i] <- Total$HIVResult[i]} 
    
    else{
        Total$HIV[i] <- as.character(Total$HIV.STATUS[i])} 
}
#From Cheryl unless desginated positive all TRU study participants are negative
Total$HIV[Total$Study=="TRU" & is.na(Total$HIV)]<-"NEG"
#From Cheryl 0 means test not done
Total$HIV<-gsub("0", "NA", Total$HIV)

Total$cd4<-NA
for (i in 1:length(Total$cd4)){
    if(!is.na(Total$CD4[i])){
        Total$cd4[i] <- as.character(Total$CD4[i])}    
    else{
        Total$cd4[i] <- as.character(Total$CD4.COUNT[i])} 
}

Total$viral.load<-NA
for (i in 1:length(Total$viral.load)){
    if(!is.na(Total$VL[i])){
        Total$viral.load[i] <- as.character(Total$VL[i])}
    
    else{
        Total$viral.load[i] <- as.character(Total$Viral.Load[i])} 
}

Total$ART<-NA
for (i in 1:length(Total$ART)){
    if(!is.null(Total$On.Art.[i])){
        Total$ART[i] <- Total$On.Art[i]}
    
    else if(!is.na(Total$ARTInitiated[i])){
        Total$ART[i] <- Total$ARTInitiated[i]}
} 
Total$ART<-gsub("0", "NO", Total$ART)

Total$IPT<-NA
for(i in 1:length(Total$IPT)){
    if(!is.na(Total$IPTInitiated[i])){
        Total$IPT[i]<-as.character(Total$IPTInitiated[i])}
        
    else if(!is.na(Total$ON.ANTI.TB.DRUGS[i])){
        Total$IPT[i] <- as.character(Total$ON.ANTI.TB.DRUGS[i])}  
    
    else {
        Total$IPT[i] <- NA}
}
Total$IPT<-gsub("0", "NO", Total$IPT)
Total$IPT<-gsub("2", NA, Total$IPT)
Total$IPT<-gsub("N/A", NA, Total$IPT)

Total$TB<-NA
for (i in 1:length(Total$TB)){
    if(!is.na(Total$QualResult[i])){
        Total$TB[i] <- as.character(Total$QualResult[i])}
    
    else if(!is.na(Total$SCREENING.ARM[i])){
        Total$TB[i] <- as.character(Total$SCREENING.ARM[i])} 
      
    else if(!is.na(Total$Screening.Arm[i])){
        Total$TB[i] <- as.character(Total$Screening.Arm[i])} 
    
    else{
        Total$TB[i] <- as.character(Total$QFT.RESULTS[i])} 
}

Total$chest.xray<-NA
for (i in 1:length(Total$chest.xray)){
    if(!is.na(Total$CXR.REPORT[i])){
        Total$chest.xray[i] <- as.character(Total$CXR.REPORT[i])}
    
    else if(!is.na(Total$chest[i])){
        Total$chest.xray[i] <- as.character(Total$chest[i])} 
      
    else if(!is.na(Total$chest.y[i])){
        Total$chest.xray[i] <- as.character(Total$chest.y[i])} 
    
    else{
        Total$chest.xray[i] <- as.character(Total$chest.x[i])} 
}

Total$HB<-NA
for (i in 1:length(Total$HB)){
    if(!is.na(Total$Hb[i])){
        Total$HB[i] <- as.character(Total$Hb[i])}
    
    else if(!is.na(Total$Gender[i])){
        Total$HB[i] <- as.character(Total$Hb.x[i])} 

    else{
        Total$HB[i] <- as.character(Total$Hb.y[i])} 
}
```

```{r tb bacteria stuff}
Total$chest.xray<-tolower(Total$chest.xray)
Total$chest.xray[grepl("abnormal|cardiomegaly", Total$chest.xray)]<-"abnormal"
Total$chest.xray[grepl("n/a|not done", Total$chest.xray)]<-NA
Total$chest.xray[grepl("no", Total$chest.xray) &! grepl("rmal", Total$chest.xray)]<-NA
Total$chest.xray[Total$chest.xray=="pending"]<-NA
Total$chest.xray[Total$chest.xray==""]<-NA

Total$gene.expert<-tolower(Total$EXPERT.RESULTS)
Total$gene.expert[grepl("n/a|no sample|error", Total$gene.expert)]<-NA
Total$gene.expert[grepl("no rif", Total$gene.expert)]<-"rif sensitive"
Total$gene.expert[Total$gene.expert==""]<-NA

Total$hain<-tolower(Total$HAIN.TEST.RESULTS)
Total$hain[grepl("invalid|n/a|no sample", Total$hain)]<-NA
Total$hain[Total$hain==""]<-NA

Total$mgit<-tolower(Total$MGIT.Culture)
Total$mgit[grepl("mott", Total$mgit)]<-"NTM"
Total$mgit[grepl("pos", Total$mgit)]<-"MTB"
Total$mgit[grepl("culture contaminated|n/a|no sample", Total$mgit)]<-NA
Total$mgit[Total$mgit==""]<-NA

Total$microscopy<-tolower(Total$FM..RESULTS)
Total$microscopy[grepl("n/a|no sample", Total$microscopy)]<-NA
Total$microscopy[Total$microscopy==""]<-NA

Total$INH.Resistant<-NA
for(i in 1:length(Total$INH.Resistant)){
    if(grepl("resistant to inh", Total$hain[i])){
        Total$INH.Resistant[i]<-1}
    
    else if(grepl("sensitive to inh", Total$hain[i])){
        Total$INH.Resistant[i]<-0}
    
    else {Total$INH.Resistant[i]<-NA}
}

Total$Rif.Resistant<-NA
for(i in 1:length(Total$Rif.Resistant)){
    if(grepl("resistant to rif", Total$hain[i])){
        Total$Rif.Resistant[i]<-1}
    
    else if(grepl("sensitive to rif", Total$hain[i])){
        Total$Rif.Resistant[i]<-0}
        
    else if(grepl("sensitive to inh and rif", Total$hain[i])){
        Total$Rif.Resistant[i]<-0}
    
    else if(grepl("rif sensitive", Total$gene.expert[i])){
        Total$Rif.Resistant[i]<-0}    

    else {Total$Rif.Resistant[i]<-NA}
}

Total$Drug.Resistant<-NA
for(i in 1:length(Total$Drug.Resistant)){
    if(!is.na(Total$INH.Resistant[i]) & Total$INH.Resistant[i]==1){
        Total$Drug.Resistant[i]<-1}
    
    else if(!is.na(Total$Rif.Resistant[i]) & Total$Rif.Resistant[i]==1){
        Total$Drug.Resistant[i]<-1}
    
    else if(!is.na(Total$gene.expert[i]) & Total$gene.expert[i]=="pos"){
        Total$Drug.Resistant[i]<-1} 
    
    else if(!is.na(Total$INH.Resistant[i]) & Total$INH.Resistant[i]=="0" &
            !is.na(Total$Rif.Resistant[i]) & Total$Rif.Resistant[i]=="0"){
        Total$Drug.Resistant[i]<-0}

    else {Total$Drug.Resistant[i]<-NA}
}
```

```{r adding in age by hand}
Total$age[Total$StudyID=="NK2738"]<-35
Total$age[Total$StudyID=="NK2812"]<-20
Total$age[Total$StudyID=="NK2819"]<-22
Total$age[Total$StudyID=="NK2841"]<-20
```

```{r implicit knowns}
Total$viral.load[Total$HIV=="NEG"]<-0
Total$WHO.STAGE[Total$HIV=="NEG"]<-0
Total$QFT[Total$TB=="ACTIVE"]<-"not done"
Total$cd4[Total$HIV=="NEG"]<-"not done"
Total$chest.xray[Total$TB=="ACTIVE"]<-"not done"
Total$RACE<-"Black African"
Total$IPT[Total$TB != "ACTIVE"]<-"NO"
Total$ART[Total$HIV == "NEG"]<-"NO"
```

```{r ineligible people}
setwd("/Applications/Old Computer/Epi Project/Data_original/")   
eligible<-read.csv("K11_ELIGIBILITY1.csv")
#2 is ineligible and 1 is eligible
ex1<-as.character(eligible$StudyID[eligible$Eligible==2])
ineligible<-read.csv("/Applications/Old Computer/Epi Project/Data_clean/QFT.missing.csv")
ex2<-as.character(ineligible$StudyID[ineligible$Comments!=""])
exclude<-c(ex1, ex2)
Total<-dplyr::filter(Total, !StudyID %in% exclude)
```

```{r Separate into Data Tables to get missing data}
#Missing values
library(dplyr)
setwd("/Applications/Old Computer/Epi Project/Data_clean/")
library(dplyr)
#Dates<-select(Total, StudyID, Date.Consented, Date.Enrolled, ART.Start.Date, DATE.ANTI.TB.STARTED, Days.on.TB.Tx)

Total<-dplyr::select(Total, -UserCode, -CurrVisit, -FollUpVisit, -StaffInitials, -HIVtestDone, -ReasonTestND, -OtherReasonTestND, -Comments, -QCStaffInitials, -EntryUserInitials, CPTs.Collected, Cell.Counts..x10.6., Baseline.Completion.Report, Sample.Storage, -Date.Enrolled, -REASON, -CPTs.Collected, -Cell.Counts..x10.6., -Baseline.Completion.Report, -Sample.Storage, -STATUS, -Visit, -RecID, -COENRLD.STUDY, -Date.Consented, -Date.Enrolled, -ART.Start.Date, -DATE.ANTI.TB.STARTED, -REFERRAL.POINT, -QFTType, -TBAntigen2, -QualResult, -SCREENING.ARM, -Screening.Arm, -QFT.RESULTS, -IPTInitiated, -ON.ANTI.TB.DRUGS, -On.ART., -ARTInitiated, -AGE, -Age, -SEX, -Gender, -Sex, -HIV.status, -HIVResult, -HIV.STATUS, -CD4, -CD4.COUNT, -VL, -Viral.Load)###Still need to remove original TB exam columns

sputum.missing<-dplyr::select(Total, StudyID, TB, HIV, CXR.REPORT, FM..RESULTS, EXPERT.RESULTS, HAIN.TEST.RESULTS, MGIT.Culture, Days.to.MGIT.Culture.)%>%
    filter(is.na(TB)|TB=="ACTIVE"|HIV=="POS")%>%
    filter(is.na(FM..RESULTS)|is.na(EXPERT.RESULTS)|is.na(HAIN.TEST.RESULTS)|is.na(MGIT.Culture))

QFT.missing<-dplyr::select(Total, StudyID, TB, NIL, TBAntigen, Mitogen, QFT)%>%
    filter(is.na(QFT))

chest.missing<-dplyr::select(Total, StudyID, TB, CXR.REPORT, Days.on.TB.Tx, HHC, Treated.for.TB.Previously.)%>%
    filter(is.na(TB)|is.na(CXR.REPORT)|is.na(HHC))

TB.missing<-dplyr::select(Total, StudyID, TB, chest.xray, gene.expert, hain, mgit, microscopy, Days.on.TB.Tx, HHC, Treated.for.TB.Previously., NIL, TBAntigen, Mitogen, QFT)%>%
    filter(is.na(TB))

Hel.missing<-dplyr::select(Total, StudyID, HelminthPositive, AscarisPositive, TricurisPositive, SchistosomaPositive, HookwormPositive, SchistosomaIntensity)%>%
    filter(is.na(HelminthPositive))

Demographic.missing<-dplyr::select(Total, StudyID, age, sex, SCREENING.SITE, RACE,
                            MAL.TEST.RESULTS, PT.RESULT, Hb)%>%
    filter(is.na(RACE) | is.na(age) | is.na(SCREENING.SITE) | is.na(Hb) | is.na(MAL.TEST.RESULTS))

HIV.missing<-dplyr::select(Total, StudyID, HIV, cd4, viral.load, WHO.STAGE)%>%
    filter(!(WHO.STAGE %in% c("1","3")))%>%
    filter(HIV!="NEG")

#have to run these at the console for whatever reason --> try the date/time thing again
write.csv(Hel.missing, "missing-helminth.csv")
write.csv(Demographic.missing, "missing-demographic.csv")
write.csv(HIV.missing, "missing-HIV.csv")
write.csv(Total, "complete-kenya.csv")
write.csv(QFT.missing, "QFT.missing.csv")
write.csv(chest.missing, "chest.missing.csv")
write.csv(TB.missing, "TB.missing.csv")
write.csv(sputum.missing, "sputum.missing.csv")

miss.var<-data.frame(colSums(is.na(Total)))
miss.donor<-data.frame(cbind(Total$StudyID, rowSums(is.na(Total))))

write.csv(miss.donor, "NAs per donor.csv")
```

```{r load and insert missing data from manual entries}
setwd("/Applications/Old Computer/Epi Project/Data_clean/")

#Fill in Helminth data from primary study files
Hel.manual<- read.csv("missing-helminth_post.csv")
Hel.manual<- filter(Hel.manual, StudyID %in% Hel.missing$StudyID)
Total2<-replace.btwn.tables(Total, Hel.manual, "StudyID", "StudyID", "HelminthPositive", "HelminthPositive")
Total2<-replace.btwn.tables(Total2, Hel.manual, "StudyID", "StudyID", "AscarisPositive", "AscarisPositive")
Total2$AscarisPositive<-as.numeric(Total2$AscarisPositive)

Total2<-replace.btwn.tables(Total2, Hel.manual, "StudyID", "StudyID", "TricurisPositive", "TricurisPositive")
Total2$TricurisPositive<-as.numeric(Total2$TricurisPositive)

Total2<-replace.btwn.tables(Total2, Hel.manual, "StudyID", "StudyID", "SchistosomaPositive", "SchistosomaPositive")
Total2$SchistosomaPositive<-as.numeric(Total2$SchistosomaPositive)

Total2<-replace.btwn.tables(Total2, Hel.manual, "StudyID", "StudyID", "HookwormPositive", "HookwormPositive")
Total2$HookwormPositive<-as.numeric(Total2$HookwormPositive)

Total2<-replace.btwn.tables(Total2, Hel.manual, "StudyID", "StudyID", "SchistosomaIntensity", "SchistosomaIntensity")

Total2<-dplyr::mutate(Total2, Number=AscarisPositive + TricurisPositive + SchistosomaPositive + HookwormPositive)

#Fill in HIV data from primary study files
HIV.manual<- read.csv("missing-HIV_post.csv")
HIV.manual<- filter(HIV.manual, StudyID %in% HIV.missing$StudyID)
Total2<-replace.btwn.tables(Total2, HIV.manual, "StudyID", "StudyID", "cd4", "cd4")
Total2<-replace.btwn.tables(Total2, HIV.manual, "StudyID", "StudyID", "viral.load", "viral.load")
Total2<-replace.btwn.tables(Total2, HIV.manual, "StudyID", "StudyID", "WHO.STAGE", "WHO.STAGE")

#Fill in QFT data
QFT.manual<- read.csv("QFT.missing_post.csv")
QFT.manual<- filter(QFT.manual, StudyID %in% QFT.missing$StudyID)
Total2<-replace.btwn.tables(Total2, QFT.manual, "StudyID", "StudyID", "NIL", "NIL")
Total2<-replace.btwn.tables(Total2, QFT.manual, "StudyID", "StudyID", "TBAntigen", "TBAntigen")
Total2<-replace.btwn.tables(Total2, QFT.manual, "StudyID", "StudyID", "Mitogen", "Mitogen")
Total2$TBAntigen<-as.numeric(Total2$TBAntigen)
Total2$Mitogen<-as.numeric(Total2$Mitogen)
Total2$NIL<-as.numeric(Total2$NIL)
Total2$QFT <- (Total2$TBAntigen-Total2$NIL)
Total2$Control <- (Total2$Mitogen-Total2$NIL)
Total2$QFT[Total2$QFT<0]<-0
Total2$Control[Total2$Control<0]<-0
Total2$QualResult[Total2$QFT>0.35]<- 1
Total2$QualResult[Total2$QualResult==1] <- as.character("LTBI")
Total2$QualResult [Total2$QFT<0.35]<- 2
Total2$QualResult[Total2$QualResult==2] <- as.character("HEALTHY CONTROL")


#fill in Demographic data
Demographic.manual<- read.csv("missing-demographic_post.csv")
Demographic.manual<- filter(Demographic.manual, StudyID %in% Demographic.missing$StudyID)
Total2<-replace.btwn.tables(Total2, Demographic.manual, 
                             "StudyID", "StudyID", "SCREENING.SITE", "SCREENING.SITE")
Total2<-replace.btwn.tables(Total2, Demographic.manual, 
                             "StudyID", "StudyID", "MAL.TEST.RESULTS", "MAL.TEST.RESULTS")


#fill in TB data
chest.manual<- read.csv("chest.missing_post.csv")
chest.manual<- filter(chest.manual, StudyID %in% chest.missing$StudyID)
sputum.manual<-read.csv("sputum.missing_post.csv")
sputum.manual<- filter(sputum.manual, StudyID %in% sputum.missing$StudyID)
Total2<-replace.btwn.tables(Total2, chest.manual, "StudyID", "StudyID", "CXR.REPORT", "CXR.REPORT")
Total2<-replace.btwn.tables(Total2, chest.manual, "StudyID", "StudyID", "HHC", "HHC")
Total2<-replace.btwn.tables(Total2, sputum.manual, "StudyID", "StudyID", "EXPERT.RESULTS", "EXPERT.RESULTS")
Total2<-replace.btwn.tables(Total2, sputum.manual, "StudyID", "StudyID", "HAIN.TEST.RESULTS", "HAIN.TEST.RESULTS")
Total2<-replace.btwn.tables(Total2, sputum.manual, "StudyID", "StudyID", "MGIT.Culture", "MGIT.Culture")
Total2<-replace.btwn.tables(Total2, sputum.manual, "StudyID", "StudyID", "Days.to.MGIT.Culture.", "Days.to.MGIT.Culture.")

write.csv(Total2, "complete-kenya-filledin.csv")

```

```{r checking for missing values again and writing over old versions}
sputum.missing<-dplyr::select(Total2, StudyID, TB, HIV, CXR.REPORT, FM..RESULTS, EXPERT.RESULTS, HAIN.TEST.RESULTS, MGIT.Culture, Days.to.MGIT.Culture.)%>%
    filter(is.na(TB)|TB=="ACTIVE"|HIV=="POS")%>%
    filter(is.na(FM..RESULTS)|is.na(EXPERT.RESULTS)|is.na(HAIN.TEST.RESULTS)|is.na(MGIT.Culture))

QFT.missing<-dplyr::select(Total2, StudyID, TB, NIL, TBAntigen, Mitogen, QFT)%>%
    filter(is.na(QFT))

chest.missing<-dplyr::select(Total2, StudyID, TB, CXR.REPORT, Days.on.TB.Tx, HHC, Treated.for.TB.Previously.)%>%
    filter(is.na(TB)|is.na(CXR.REPORT)|is.na(HHC))

TB.missing<-dplyr::select(Total2, StudyID, TB, chest.xray, gene.expert, hain, mgit, microscopy, Days.on.TB.Tx, HHC, Treated.for.TB.Previously., NIL, TBAntigen, Mitogen, QFT)%>%
    filter(is.na(TB))

Hel.missing<-dplyr::select(Total2, StudyID, HelminthPositive, AscarisPositive, TricurisPositive, SchistosomaPositive, HookwormPositive, SchistosomaIntensity)%>%
    filter(is.na(HelminthPositive))

Demographic.missing<-dplyr::select(Total2, StudyID, age, sex, SCREENING.SITE, RACE,
                            MAL.TEST.RESULTS, PT.RESULT, Hb)%>%
    filter(is.na(RACE) | is.na(age) | is.na(SCREENING.SITE) | is.na(Hb) | is.na(MAL.TEST.RESULTS))

HIV.missing<-dplyr::select(Total2, StudyID, HIV, cd4, viral.load, WHO.STAGE)%>%
    filter(!(WHO.STAGE %in% c("1","3")))%>%
    filter(HIV!="NEG")

#have to run these at the console for whatever reason --> try the date/time thing again
write.csv(Hel.missing, "missing-helminth.csv")
write.csv(Demographic.missing, "missing-demographic.csv")
write.csv(HIV.missing, "missing-HIV.csv")
write.csv(Total2, "complete-kenya.csv")
write.csv(QFT.missing, "QFT.missing.csv")
write.csv(chest.missing, "chest.missing.csv")
write.csv(TB.missing, "TB.missing.csv")
write.csv(sputum.missing, "sputum.missing.csv")

miss.var<-data.frame(colSums(is.na(Total2)))
miss.donor<-data.frame(cbind(Total2$StudyID, rowSums(is.na(Total2))))
```

I checked these against primary study records
NK2162 coded in NKS Kato Katz as positive with eggs = 72 but it’s actually negative according to study files  

2323 SM+ 144/168/96/24  
HC 10/0.08/0.04  

```{r Making manual edits}
Total2$HelminthPositive[Total2$StudyID=="NK2162"]<-0
Total2$SchistosomaPositive[Total2$StudyID=="NK2162"]<-0
Total2$SchistosomaIntensity[Total2$StudyID=="NK2162"]<-0

Total2$QFT[Total2$StudyID=="NK2323"]<-0.04
Total2$Control[Total2$StudyID=="NK2323"]<-9.96
Total2$TB[Total2$StudyID=="NK2323"]<-"HEALTHY CONTROL"
Total2$SchistosomaIntensity[Total2$StudyID=="NK2323"]<-108

Total2$HelminthPositive[Total2$StudyID=="NK2394"]<-1
Total2$SchistosomaPositive[Total2$StudyID=="NK2394"]<-1
Total2$SchistosomaIntensity[Total2$StudyID=="NK2394"]<-96/4

setwd("/Applications/Old Computer/Epi Project/Data_clean/")
write.csv(Total2, "complete-kenya-filledin.csv")
```

